# Generated by Django 6.1 on 2026-08-30 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='updataed_at',
            new_name='updated_at',
        ),
    ]
